/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body - W5500 TCP Echo Server
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "w5500_conf.h"
#include "wizchip_conf.h"
#include "w5500.h"
#include "socket.h"
#include "lcd_i2c.h"
// #include "p10.h"      // P10 disabled - pins reused for W25Q128
#include "w25q128.h"
// #include "ds1302.h"   // DS1302 disabled - JTAG pins preserved
#include "wiegand.h"
#include "relay.h"

/* Required by startup_stm32f103xx.S */
extern "C" void SystemInit(void)
{
    /* Empty - clock config done later in main */
}

/* ============================================================================
 * Network Configuration
 * ============================================================================ */

#define SOCKET_TCP      0               // Socket number for TCP
#define TCP_PORT        5000            // TCP Server port
#define DATA_BUF_SIZE   2048            // Data buffer size

/* Network Info */
static wiz_NetInfo gNetInfo = {
    .mac  = {0x00, 0x08, 0xDC, 0x12, 0x34, 0x56},   // MAC Address
    .ip   = {192, 168, 1, 100},                      // IP Address
    .sn   = {255, 255, 255, 0},                      // Subnet Mask
    .gw   = {192, 168, 1, 1},                        // Gateway
    .dns  = {8, 8, 8, 8},                            // DNS Server
    .dhcp = NETINFO_STATIC                           // Static IP
};

/* Data buffer */
static uint8_t gDataBuf[DATA_BUF_SIZE];

/* ============================================================================
 * W5500 Callback Functions
 * ============================================================================ */

/**
 * @brief  Chip Select callback
 */
void W5500_Select(void)
{
    W5500_CS_LOW();
}

/**
 * @brief  Chip Deselect callback
 */
void W5500_Deselect(void)
{
    W5500_CS_HIGH();
}

/**
 * @brief  SPI Read byte callback
 */
uint8_t W5500_ReadByte(void)
{
    return W5500_SPI_ReadWrite(0xFF);
}

/**
 * @brief  SPI Write byte callback
 */
void W5500_WriteByte(uint8_t byte)
{
    W5500_SPI_ReadWrite(byte);
}

/**
 * @brief  SPI Read burst callback
 */
void W5500_ReadBurst(uint8_t* pBuf, uint16_t len)
{
    for(uint16_t i = 0; i < len; i++) {
        pBuf[i] = W5500_SPI_ReadWrite(0xFF);
    }
}

/**
 * @brief  SPI Write burst callback
 */
void W5500_WriteBurst(uint8_t* pBuf, uint16_t len)
{
    for(uint16_t i = 0; i < len; i++) {
        W5500_SPI_ReadWrite(pBuf[i]);
    }
}

/* ============================================================================
 * W5500 Initialization
 * ============================================================================ */

/**
 * @brief  Initialize W5500 chip
 */
void W5500_Init(void)
{
    /* Initialize GPIO and SPI */
    W5500_GPIO_Init();
    W5500_SPI_Init();
    
    /* Hardware reset */
    W5500_Reset();
    
    /* Register SPI callbacks */
    reg_wizchip_cs_cbfunc(W5500_Select, W5500_Deselect);
    reg_wizchip_spi_cbfunc(W5500_ReadByte, W5500_WriteByte);
    reg_wizchip_spiburst_cbfunc(W5500_ReadBurst, W5500_WriteBurst);
    
    /* Initialize socket buffer size (2KB each) */
    uint8_t memsize[2][8] = {
        {2, 2, 2, 2, 2, 2, 2, 2},    // RX buffer sizes
        {2, 2, 2, 2, 2, 2, 2, 2}     // TX buffer sizes
    };
    
    if(ctlwizchip(CW_INIT_WIZCHIP, (void*)memsize) == -1) {
        /* Initialization failed */
        while(1);
    }
    
    /* Set network information */
    ctlnetwork(CN_SET_NETINFO, (void*)&gNetInfo);
}

/* ============================================================================
 * TCP Echo Server
 * ============================================================================ */

/**
 * @brief  TCP Echo Server - Receive data and send it back
 * @param  sn: Socket number
 * @param  port: TCP port number
 * @retval Status
 */
int32_t TCP_EchoServer(uint8_t sn, uint16_t port)
{
    int32_t ret;
    uint16_t size;
    
    switch(getSn_SR(sn))
    {
        case SOCK_ESTABLISHED:
            /* Check if data received */
            if((size = getSn_RX_RSR(sn)) > 0)
            {
                if(size > DATA_BUF_SIZE) {
                    size = DATA_BUF_SIZE;
                }
                
                /* Receive data */
                ret = recv(sn, gDataBuf, size);
                
                if(ret <= 0) {
                    return ret;
                }
                
                /* Send data back (Echo) */
                ret = send(sn, gDataBuf, ret);
                
                if(ret < 0) {
                    close(sn);
                    return ret;
                }
                
                /* Display received data on LCD */
                LCD_Clear();
                LCD_SetCursor(0, 0);
                LCD_Print("Recv:");
                LCD_PrintInt(size);
                LCD_Print("B");
                
                LCD_SetCursor(0, 1);
                /* Display first 16 chars of received data */
                gDataBuf[ret] = '\0';  // Null-terminate
                if(ret > 16) {
                    gDataBuf[16] = '\0';  // Limit to 16 chars for LCD
                }
                LCD_Print((const char*)gDataBuf);
                
                /* Log received data to W25Q128 Flash */
                if(W25Q_IsConnected()) {
                    W25Q_LogWrite(W25Q_LOG_TCP_RECV, gDataBuf, (ret > 56) ? 56 : (uint8_t)ret);
                }
            }
            break;
            
        case SOCK_CLOSE_WAIT:
            /* Disconnect request from client */
            disconnect(sn);
            break;
            
        case SOCK_CLOSED:
            /* Open socket as TCP */
            ret = socket(sn, Sn_MR_TCP, port, 0x00);
            if(ret != sn) {
                return ret;
            }
            break;
            
        case SOCK_INIT:
            /* Listen for incoming connections */
            ret = listen(sn);
            if(ret != SOCK_OK) {
                return ret;
            }
            break;
            
        default:
            break;
    }
    
    return 1;
}

/* ============================================================================
 * System Clock Configuration
 * ============================================================================ */

/**
 * @brief  Configure system clock to 72MHz using HSE (8MHz) + PLL (x9)
 */
/**
 * @brief  Simple delay
 */
static void delay_ms(uint32_t ms)
{
    /* Approximate: works at both 8MHz and 72MHz */
    for(volatile uint32_t i = 0; i < ms * 7200; i++);
}

/**
 * @brief  Initialize PC13 LED (Blue Pill onboard LED)
 */
static void LED_Init(void)
{
    RCC->APB2ENR |= (1 << 4);           // GPIOC clock enable
    /* PC13 as Output Push-Pull, 2MHz */
    GPIOC->CRH &= ~(0x0F << 20);        // Clear PC13 config
    GPIOC->CRH |= (0x02 << 20);         // Output 2MHz, Push-Pull
}

static void LED_On(void)  { GPIOC->BRR  = (1 << 13); }  // Active low
static void LED_Off(void) { GPIOC->BSRR = (1 << 13); }

static void LED_Blink(uint8_t times, uint32_t ms)
{
    for(uint8_t i = 0; i < times; i++) {
        LED_On(); delay_ms(ms);
        LED_Off(); delay_ms(ms);
    }
}

void SystemClock_Config(void)
{
    /* Enable HSE (High-Speed External oscillator) */
    RCC->CR |= (1 << 16);               // HSEON
    
    /* Wait HSERDY with timeout */
    volatile uint32_t timeout = 100000;
    while(!(RCC->CR & (1 << 17)) && --timeout);
    
    if(timeout == 0) {
        /* HSE failed - stay on HSI 8MHz */
        return;
    }
    
    /* Enable Prefetch Buffer & set Flash latency to 2 wait states (for 72MHz) */
    FLASH->ACR |= (1 << 4);             // PRFTBE: Prefetch buffer enable
    FLASH->ACR &= ~(0x07);              // Clear latency bits
    FLASH->ACR |= (0x02);               // 2 wait states (48MHz < SYSCLK <= 72MHz)
    
    /* Configure PLL:
     * - PLL source = HSE (8MHz)
     * - PLL multiplier = x9
     * - SYSCLK = 8MHz * 9 = 72MHz
     */
    RCC->CFGR &= ~((1 << 16) | (0xF << 18));  // Clear PLLSRC and PLLMUL
    RCC->CFGR |= (1 << 16);             // PLLSRC = HSE
    RCC->CFGR |= (0x7 << 18);           // PLLMUL = x9 (0111)
    
    /* Configure bus clocks:
     * - AHB  = SYSCLK / 1 = 72MHz
     * - APB1 = SYSCLK / 2 = 36MHz (max 36MHz)
     * - APB2 = SYSCLK / 1 = 72MHz
     */
    RCC->CFGR &= ~((0xF << 4) | (0x7 << 8) | (0x7 << 11));  // Clear HPRE, PPRE1, PPRE2
    RCC->CFGR |= (0x4 << 8);            // PPRE1 = /2 (100)
    
    /* Enable PLL */
    RCC->CR |= (1 << 24);               // PLLON
    while(!(RCC->CR & (1 << 25)));       // Wait PLLRDY
    
    /* Select PLL as system clock source */
    RCC->CFGR &= ~(0x3 << 0);           // Clear SW
    RCC->CFGR |= (0x2 << 0);            // SW = PLL
    while(((RCC->CFGR >> 2) & 0x3) != 0x2);  // Wait SWS = PLL
}

/* ============================================================================
 * Main Function
 * ============================================================================ */

int main(void)
{
    /* Initialize LED for debug */
    LED_Init();
    LED_Blink(2, 100);  // 2 blinks = MCU started
    
    /* Initialize system clock to 72MHz */
    SystemClock_Config();
    LED_Blink(3, 100);  // 3 blinks = Clock configured
    
    /* Initialize W5500 */
    W5500_Init();
    LED_Blink(4, 100);  // 4 blinks = W5500 initialized
    
    /* Verify W5500 - read chip version (should be 0x04) */
    uint8_t ver = getVERSIONR();
    if(ver == 0x04) {
        LED_Blink(5, 100);  // 5 blinks = W5500 SPI OK
    } else {
        // Fast blink = SPI error
        for(int i = 0; i < 20; i++) {
            LED_On(); delay_ms(50);
            LED_Off(); delay_ms(50);
        }
    }
    
    /* Open TCP socket and start listening BEFORE entering loop */
    socket(SOCKET_TCP, Sn_MR_TCP, TCP_PORT, 0x00);
    listen(SOCKET_TCP);
    LED_Blink(6, 100);  // 6 blinks = TCP listening
    
    /* Initialize LCD (auto-skip if not connected) */
    LCD_Init();
    if(LCD_IsConnected()) {
        LCD_Clear();
        LCD_SetCursor(0, 0);
        if(ver == 0x04) {
            LCD_Print("W5500 OK v");
            LCD_PrintInt(ver);
        } else {
            LCD_Print("W5500 ERR:");
            LCD_PrintInt(ver);
        }
        LCD_SetCursor(0, 1);
        LCD_Print("192.168.1.100");
    }
    
    /* Initialize W25Q128 SPI Flash (reuses P10 pins PB12-PB15) */
    uint8_t flashOk = W25Q_Init();
    if(flashOk) {
        W25Q_LogInit();
        /* Log boot event */
        const char *bootMsg = "Boot OK";
        W25Q_LogWrite(W25Q_LOG_BOOT, (const uint8_t *)bootMsg, 7);
        
        if(LCD_IsConnected()) {
            LCD_SetCursor(0, 1);
            LCD_Print("Flash OK Boot:");
            LCD_PrintInt((int)W25Q_GetBootCount());
        }
    } else {
        if(LCD_IsConnected()) {
            LCD_SetCursor(0, 1);
            LCD_Print("Flash: N/A");
        }
    }
    
    /* DS1302 RTC disabled — JTAG pins preserved */
    
    /* Initialize Wiegand RFID Reader (2 ports: PA3/PA8, PA0/PA1) */
    WG_Init();
    LED_Blink(8, 100);  // 8 blinks = Wiegand ready
    
    /* Initialize Relay outputs (PA9-PA12, 4 channels) */
    RELAY_Init();
    LED_Blink(9, 100);  // 9 blinks = Relay ready
    
    /* Main loop - Run TCP Echo Server + heartbeat LED + RTC display + Wiegand + Relay */
    while(1)
    {
        TCP_EchoServer(SOCKET_TCP, TCP_PORT);
        
        /* Process relay auto-off timers */
        RELAY_Process();
        
        /* Poll all Wiegand reader ports */
        uint8_t wgResult = WG_Process();
        if(wgResult) {
            /* Check each port for new data */
            for(uint8_t wgPort = 0; wgPort < WG_NUM_PORTS; wgPort++) {
                WG_CardData_t card;
                if(WG_GetCard(wgPort, &card)) {
                    /* Display on LCD */
                    if(LCD_IsConnected()) {
                        LCD_Clear();
                        LCD_SetCursor(0, 0);
                        if(card.valid) {
                            char cardStr[28];
                            WG_FormatCard(&card, cardStr);
                            LCD_Print(cardStr);
                        } else {
                            LCD_Print("P");
                            LCD_PrintInt(card.port);
                            LCD_Print(" ERR ");
                            LCD_PrintInt(card.bitCount);
                            LCD_Print("b");
                        }
                        
                        /* Show relay status on line 2 */
                        char relayBuf[7];
                        RELAY_FormatStatus(relayBuf);
                        LCD_SetCursor(0, 1);
                        LCD_Print(relayBuf);
                    }
                    
                    /* Activate relay for the corresponding port (pulse ~3s) */
                    if(card.valid && card.port < RELAY_NUM_CHANNELS) {
                        RELAY_Pulse(card.port, 2160000);  // ~3s at 72MHz loop
                    }
                    
                    /* Log card to W25Q128 Flash */
                    if(W25Q_IsConnected()) {
                        uint8_t logBuf[56];
                        char cardStr[28];
                        WG_FormatCard(&card, cardStr);
                        uint8_t len = 0;
                        while(cardStr[len] && len < 56) len++;
                        memcpy(logBuf, cardStr, len);
                        W25Q_LogWrite(W25Q_LOG_SYSTEM, logBuf, len);
                    }
                }
            }
        }
        
        /* Heartbeat - toggle LED every ~1s */
        static uint32_t cnt = 0;
        if(++cnt > 100000) {
            cnt = 0;
            GPIOC->ODR ^= (1 << 13);
            
            /* Update relay status on LCD every heartbeat (~1s) */
            if(LCD_IsConnected()) {
                /* Show relay status on line 2 */
                char relayBuf[7];
                RELAY_FormatStatus(relayBuf);
                LCD_SetCursor(9, 1);
                LCD_Print(relayBuf);
            }
        }
    }
}
