/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body - W5500 TCP Echo Server
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "w5500_conf.h"
#include "wizchip_conf.h"
#include "w5500.h"
#include "socket.h"
#include "lcd_i2c.h"

/* ============================================================================
 * Network Configuration
 * ============================================================================ */

#define SOCKET_TCP      0               // Socket number for TCP
#define TCP_PORT        5000            // TCP Server port
#define DATA_BUF_SIZE   2048            // Data buffer size

/* Network Info */
static wiz_NetInfo gNetInfo = {
    .mac  = {0x00, 0x08, 0xDC, 0x12, 0x34, 0x56},   // MAC Address
    .ip   = {192, 168, 1, 100},                      // IP Address
    .sn   = {255, 255, 255, 0},                      // Subnet Mask
    .gw   = {192, 168, 1, 1},                        // Gateway
    .dns  = {8, 8, 8, 8},                            // DNS Server
    .dhcp = NETINFO_STATIC                           // Static IP
};

/* Data buffer */
static uint8_t gDataBuf[DATA_BUF_SIZE];

/* ============================================================================
 * W5500 Callback Functions
 * ============================================================================ */

/**
 * @brief  Chip Select callback
 */
void W5500_Select(void)
{
    W5500_CS_LOW();
}

/**
 * @brief  Chip Deselect callback
 */
void W5500_Deselect(void)
{
    W5500_CS_HIGH();
}

/**
 * @brief  SPI Read byte callback
 */
uint8_t W5500_ReadByte(void)
{
    return W5500_SPI_ReadWrite(0xFF);
}

/**
 * @brief  SPI Write byte callback
 */
void W5500_WriteByte(uint8_t byte)
{
    W5500_SPI_ReadWrite(byte);
}

/**
 * @brief  SPI Read burst callback
 */
void W5500_ReadBurst(uint8_t* pBuf, uint16_t len)
{
    for(uint16_t i = 0; i < len; i++) {
        pBuf[i] = W5500_SPI_ReadWrite(0xFF);
    }
}

/**
 * @brief  SPI Write burst callback
 */
void W5500_WriteBurst(uint8_t* pBuf, uint16_t len)
{
    for(uint16_t i = 0; i < len; i++) {
        W5500_SPI_ReadWrite(pBuf[i]);
    }
}

/* ============================================================================
 * W5500 Initialization
 * ============================================================================ */

/**
 * @brief  Initialize W5500 chip
 */
void W5500_Init(void)
{
    /* Initialize GPIO and SPI */
    W5500_GPIO_Init();
    W5500_SPI_Init();
    
    /* Hardware reset */
    W5500_Reset();
    
    /* Register SPI callbacks */
    reg_wizchip_cs_cbfunc(W5500_Select, W5500_Deselect);
    reg_wizchip_spi_cbfunc(W5500_ReadByte, W5500_WriteByte);
    reg_wizchip_spiburst_cbfunc(W5500_ReadBurst, W5500_WriteBurst);
    
    /* Initialize socket buffer size (2KB each) */
    uint8_t memsize[2][8] = {
        {2, 2, 2, 2, 2, 2, 2, 2},    // RX buffer sizes
        {2, 2, 2, 2, 2, 2, 2, 2}     // TX buffer sizes
    };
    
    if(ctlwizchip(CW_INIT_WIZCHIP, (void*)memsize) == -1) {
        /* Initialization failed */
        while(1);
    }
    
    /* Set network information */
    ctlnetwork(CN_SET_NETINFO, (void*)&gNetInfo);
}

/* ============================================================================
 * TCP Echo Server
 * ============================================================================ */

/**
 * @brief  TCP Echo Server - Receive data and send it back
 * @param  sn: Socket number
 * @param  port: TCP port number
 * @retval Status
 */
int32_t TCP_EchoServer(uint8_t sn, uint16_t port)
{
    int32_t ret;
    uint16_t size;
    
    switch(getSn_SR(sn))
    {
        case SOCK_ESTABLISHED:
            /* Check if data received */
            if((size = getSn_RX_RSR(sn)) > 0)
            {
                if(size > DATA_BUF_SIZE) {
                    size = DATA_BUF_SIZE;
                }
                
                /* Receive data */
                ret = recv(sn, gDataBuf, size);
                
                if(ret <= 0) {
                    return ret;
                }
                
                /* Send data back (Echo) */
                ret = send(sn, gDataBuf, ret);
                
                if(ret < 0) {
                    close(sn);
                    return ret;
                }
                
                /* Display received data on LCD */
                LCD_Clear();
                LCD_SetCursor(0, 0);
                LCD_Print("Recv:");
                LCD_PrintInt(size);
                LCD_Print("B");
                
                LCD_SetCursor(0, 1);
                /* Display first 16 chars of received data */
                gDataBuf[ret] = '\0';  // Null-terminate
                if(ret > 16) {
                    gDataBuf[16] = '\0';  // Limit to 16 chars for LCD
                }
                LCD_Print((const char*)gDataBuf);
            }
            break;
            
        case SOCK_CLOSE_WAIT:
            /* Disconnect request from client */
            disconnect(sn);
            break;
            
        case SOCK_CLOSED:
            /* Open socket as TCP */
            ret = socket(sn, Sn_MR_TCP, port, 0x00);
            if(ret != sn) {
                return ret;
            }
            break;
            
        case SOCK_INIT:
            /* Listen for incoming connections */
            ret = listen(sn);
            if(ret != SOCK_OK) {
                return ret;
            }
            break;
            
        default:
            break;
    }
    
    return 1;
}

/* ============================================================================
 * Main Function
 * ============================================================================ */

int main(void)
{
    /* Initialize system clock (if needed) */
    // SystemClock_Config();
    
    /* Initialize LCD */
    LCD_Init();
    LCD_Clear();
    LCD_SetCursor(0, 0);
    LCD_Print("TCP Echo Server");
    LCD_SetCursor(0, 1);
    LCD_Print("192.168.1.100");
    
    /* Initialize W5500 */
    W5500_Init();
    
    /* Main loop - Run TCP Echo Server */
    while(1)
    {
        TCP_EchoServer(SOCKET_TCP, TCP_PORT);
    }
}
